rootProject.name = "MoneyManager"
include(":app")

include(":core:common")
include(":core:common-android")
include(":core:network")
include(":core:database")
include(":core:datastore")
include(":core:designsystem")

include(":currency:currency-di")
include(":currency:currency-data:currency-data-contract")
include(":currency:currency-data:currency-data-impl")
include(":currency:currency-domain:currency-domain-model")
include(":currency:currency-domain:currency-domain-contract")
include(":currency:currency-domain:currency-domain-impl")
include(":currency:currency-observer:currency-observer-contract")
include(":currency:currency-observer:currency-observer-impl")
include(":currency:currency-ui")

include(":budget:budget-di")
include(":budget:budget-data:budget-data-contract")
include(":budget:budget-data:budget-data-impl")
include(":budget:budget-domain:budget-domain-model")
include(":budget:budget-domain:budget-domain-contract")
include(":budget:budget-domain:budget-domain-impl")
include(":budget:budget-ui")

include(":user-info:data:contract")
include(":user-info:data:impl")
include(":user-info:di")
include(":user-info:domain:contract")
include(":user-info:domain:impl")
include(":user-info:domain:model")

include(":transaction:di")
include(":transaction:data:contract")
include(":transaction:data:impl")
include(":transaction:regular:data:impl")
include(":transaction:domain:contract")
include(":transaction:domain:impl")
include(":transaction:domain:model")
include(":transaction:regular")
include(":transaction:ui")
include(":transaction:regular:data:contract")
include(":transaction:regular:data:impl")
include(":transaction:regular:domain:model")
include(":transaction:regular:domain:contract")
include(":transaction:regular:domain:impl")
include(":transaction:regular:di")
include(":transaction:regular:ui")

include(":category:category-di")
include(":category:category-data")
include(":category:category-domain")
include(":category:category-data:category-data-impl")
include(":category:category-data:category-data-contract")
include(":category:category-domain:category-domain-contract")
include(":category:category-domain:category-domain-model")
include(":category:category-domain:category-domain-impl")
include(":category:category-ui")

include(":billing:billing-data:billing-data-contract")
include(":billing:billing-data:billing-data-impl")
include(":billing:billing-domain:billing-domain-contract")
include(":billing:billing-domain:billing-domain-model")
include(":billing:billing-domain:billing-domain-impl")
include(":billing:billing-di")

include(":backup:backup-data:backup-data-contract")
include(":backup:backup-data:backup-data-impl")
include(":backup:backup-domain:backup-domain-contract")
include(":backup:backup-domain:backup-domain-model")
include(":backup:backup-domain:backup-domain-impl")
include(":backup:backup-di")

include(":statistics:statistics-domain:statistics-domain-model")
include(":statistics:statistics-ui")

include(":analytics:analytics-di")
include(":profile:profile-ui")
include(":incomeexpense:incomeexpense-ui")
include(":settings:settings-ui")

pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
