rootProject.name = "MoneyManager"
include(":app")

include(":core:common")
include(":core:common-android")
include(":core:network")
include(":core:database")
include(":core:datastore")
include(":core:designsystem")

include(":currency:di")
include(":currency:data:contract")
include(":currency:data:impl")
include(":currency:domain:model")
include(":currency:domain:contract")
include(":currency:domain:impl")
include(":currency:observer:contract")
include(":currency:observer:impl")
include(":currency:ui")

include(":budget:di")
include(":budget:data:contract")
include(":budget:data:impl")
include(":budget:domain:model")
include(":budget:domain:contract")
include(":budget:domain:impl")
include(":budget:ui")

include(":user-info:data:contract")
include(":user-info:data:impl")
include(":user-info:di")
include(":user-info:domain:contract")
include(":user-info:domain:impl")
include(":user-info:domain:model")

include(":transaction:di")
include(":transaction:data:contract")
include(":transaction:data:impl")
include(":transaction:regular:data:impl")
include(":transaction:domain:contract")
include(":transaction:domain:impl")
include(":transaction:domain:model")
include(":transaction:regular")
include(":transaction:ui")
include(":transaction:regular:data:contract")
include(":transaction:regular:data:impl")
include(":transaction:regular:domain:model")
include(":transaction:regular:domain:contract")
include(":transaction:regular:domain:impl")
include(":transaction:regular:di")
include(":transaction:regular:ui")

include(":category:category-di")
include(":category:category-data")
include(":category:category-domain")
include(":category:category-data:category-data-impl")
include(":category:category-data:category-data-contract")
include(":category:category-domain:category-domain-contract")
include(":category:category-domain:category-domain-model")
include(":category:category-domain:category-domain-impl")
include(":category:category-ui")

include(":billing:data:contract")
include(":billing:data:impl")
include(":billing:domain:contract")
include(":billing:domain:model")
include(":billing:domain:impl")
include(":billing:di")

include(":backup:data:contract")
include(":backup:data:impl")
include(":backup:domain:contract")
include(":backup:domain:model")
include(":backup:domain:impl")
include(":backup:di")

include(":statistics:domain:model")
include(":statistics:ui")

include(":analytics:di")
include(":profile:ui")
include(":incomeexpense:ui")
include(":settings:ui")

pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
